# Generated by Django 2.1.7 on 2019-02-27 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='document',
        ),
    ]
