# Generated by Django 2.1.7 on 2019-02-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_image_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='document',
            field=models.ImageField(null=True, upload_to='documents/'),
        ),
    ]
