# Generated by Django 2.1.7 on 2019-02-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_image_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='document',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
    ]
