# Generated by Django 2.1.7 on 2019-02-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20190227_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
