# Generated by Django 2.1.7 on 2019-02-27 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20190227_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Image')),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Dataset')),
            ],
        ),
    ]
